<?php

/**
 * Implements hook_form_alter().
 */
function wwm_sticky_buttons_form_alter(&$form, &$form_state, $form_id) {
  $module_filter_state = module_exists('module_filter');
  $admin_path_state = path_is_admin($current_path = current_path());
  if($admin_path_state && !($module_filter_state && $current_path === 'admin/modules')) {
    // Add class.
    $form['actions']['#attributes']['class'][] = 'my-sticky-element';
  }
}

/**
 * Implements hook_media_edit_multiple_form_alter().
 */
function wwm_sticky_buttons_media_edit_multiple_form_alter(&$form) {
  $form['actions'] = $form['buttons'];
  $form['actions']['#type'] = 'actions';
  unset($form['buttons']);

  $form_state = array();

  wwm_sticky_buttons_form_alter($form, $form_state, 'media_edit_multiple_form');
}
